name: Post welcome comment

on:
  pull_request:
    types: [opened]  # Se déclenche uniquement à l'ouverture d'une PR

permissions:
  pull-requests: write  # Nécessaire pour pouvoir écrire un commentaire sur la PR

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Post a comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Merci pour votre PR 🚀 Nous allons la réviser dès que possible !"
            })

